spring:
  datasource:
    url: ${DB_URL}
    port: ${DB_PORT:5432}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: discord
logging:
  level:
    root: info

discord:
  token: ${DISCORD_TOKEN}
  channel-id: ${DISCORD_CHANNEL_ID}

dns.name: ${DNS_NAME}

reports.path: ${REPORTS_PATH:reports}

services:
  bot-activity-enabled: ${ENABLE_BOT_ACTIVITY:false}    # Controls bot activity updates and Discord message/image sending
  events-enabled: ${ENABLE_EVENTS:false}    # Controls event processing from game server
  map-enabled: ${ENABLE_MAP:false}    # Controls GeoIP, WorldMapGenerator and map functionality

geoip:
  license-key: ${MAXMIND_LICENSE_KEY}
  data-dir: data/geoip

map:
  types: ${MAP_TYPES:HEATMAP} # Possible values: ALL, HEATMAP, LOCATION
  show-names: ${MAP_NAMES:false}
  colors:
    background-rgb: 32,33,36
    border-rgb: 70,70,70
    no-data-rgb: 50,50,50
    gradient:
      min-red: 255
      min-green: 216
      min-blue: 216
      max-red: 128
      max-green: 0
      max-blue: 0
    dots:
      color-rgb: 0,128,255
      border-color-rgb: 0,128,255
      opacity: 180
      border-opacity: 200
      size: 6


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:mohh_db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS public && CREATE SCHEMA IF NOT EXISTS discord;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-populate.yaml
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
