server:
  port: 8082

spring:
  datasource:
    url: ${DB_URL}
    port: ${DB_PORT:5432}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

discord.token: ${DISCORD_TOKEN}

dns.name: ${DNS_NAME}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:mohh_db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS public;
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
